/**
 * Created by samk on 24/02/2017.
 */

const ActionTypes = {
  INPUT_KEY_PRESS: 'INPUT_KEY_PRESS',
  INPUT_ENTER: 'INPUT_ENTER',
  INPUT_BACKSPACE: 'INPUT_BACKSPACE',
  INPUT_CHANGE: 'INPUT_CHANGE',

  PROTOCOL_TICK: 'PROTOCOL_TICK',
  PROTOCOL_FLUSH: 'PROTOCOL_FLUSH',
  PROTOCOL_CONNECT: 'PROTOCOL_CONNECT',

  EVENT_SOURCE_MESSAGE: 'EVENT_SOURCE_MESSAGE',
  EVENT_SOURCE_ERROR: 'EVENT_SOURCE_ERROR',
  EVENT_SOURCE_OPEN: 'EVENT_SOURCE_OPEN',

  PEER_CHAR_CODE: 'PEER_CHAR_CODE',
  PEER_ENTER_MESSAGE: 'PEER_ENTER_MESSAGE',
  PEER_BACKSPACE: 'PEER_BACKSPACE',
  PEER_CHANGE_MESSAGE: 'PEER_CHANGE_MESSAGE'
};

export default ActionTypes